name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Xvfb
        run: sudo apt-get install xvfb -y

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Set DISPLAY variable
        run: export DISPLAY=:99

      # Ejecuta las pruebas del frontend una sola vez con Chrome en el entorno con Xvfb
      - name: Run frontend tests with Chrome
        run: npm test
        working-directory: frontend

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Run backend tests
        run: npm test
        working-directory: backend

     
